### ISSUE TITLE
Feature request: a requirements file

### ISSUE THREAD

**Issue by raybellwaves** [MicrosoftDocs/ml-basics#7]
https://github.com/MicrosoftDocs/ml-basics/blob/master/local-setup.md states which packages to use. It would be helpful to provide a requirements file in either a .txt for .yaml form to simplify package installation.

**Comment by GraemeMalcolm** [comment]
Good suggestion. I added instructions to do this.

**Comment by hansmbakker** [comment]
@GraemeMalcolm could you please, instead, add `requirements.txt` as a file to the root of the repository so that services like https://mybinder.org/ can automatically pick them up?

https://mybinder.org/ can generate Jupyter execution environments for github repositories automatically, so that users can work with the notebooks without setting up an environment themselves.
